default_settings:
  trainer_type: poca
  hyperparameters:
    batch_size: 1024
    buffer_size: 10240
    learning_rate: 5e-4
    beta: 3e-3
    epsilon: 0.15
    lambd: 0.97
    num_epoch: 4
    learning_rate_schedule: linear
  network_settings:
    normalize: false
    hidden_units: 256
    num_layers: 2
    vis_encode_type: simple
  reward_signals:
    extrinsic:
      gamma: 0.99
      strength: 1.0
  keep_checkpoints: 5
  max_steps: 5e7
  time_horizon: 512
  summary_freq: 2000
  self_play:
    save_steps: 25000
    team_change: 200000
    swap_steps: 2000
    window: 10
    play_against_latest_model_ratio: 0.5
    initial_elo: 1200.0

behaviors:
  StrikerAI:
    hyperparameters:
      learning_rate: 0.0004
      beta: 0.004
    reward_signals:
      extrinsic:
        strength: 1.2

  DefenderAI:
    hyperparameters:
      learning_rate: 0.00025
      epsilon: 0.15
    reward_signals:
      extrinsic:
        strength: 1.1

  GoalieAI:
    hyperparameters:
      learning_rate: 0.0002
      lambd: 0.9
    reward_signals:
      extrinsic:
        strength: 1.3
